raw_to_nyu40 = {'socket': 39, 
                'whiteboard': 29, 
                'shelf': 39, 
                'heater': 38, 
                'windowsill': 37, 
                'windowframe': 8, 
                'bottle': 39, 
                'notebook': 22, 
                'laptop stand': 39, 
                'telephone': 39,
                'trash can': 38, 
                'light switch': 37, 
                'tissue box': 39, 
                'monitor': 39, 
                'pc': 39,
                'keyboard': 39, 
                'multi socket': 39, 
                'mouse': 39, 
                'standing lamp': 34, 
                'beam': 37, 
                'light switch': 37, 
                'pipe': 39}