raw_to_nyu40 = {'socket': 39, 
                'whiteboard': 29, 
                'shelf': 39, 
                'heater': 38, 
                'windowsill': 37, 
                'windowframe': 8, 
                'bottle': 39, 
                'notebook': 22, 
                'laptop stand': 39, 
                'telephone': 39,
                'trash can': 38, 
                'light switch': 37, 
                'tissue box': 39, 
                'monitor': 39, 
                'pc': 39,
                'keyboard': 39, 
                'multi socket': 39, 
                'mouse': 39, 
                'standing lamp': 34, 
                'beam': 37, 
                'light switch': 37, 
                'pipe': 39,
                
                 ### 0d2ee665be
                'office chair': 4,
                'sweater': 20,
                'backpack': 36, 'duffel bag': 36,
                'nightstand': 31,
                'baseball cap': 39,
                'laundry hamper': 39,
                'jacket': 39,
                'kitchen utensil': 37,
                'cup': 39,
                'scissors': 39,
                'cutting board': 39,
                'kitchen cabinet': 2,
                'kitchen counter': 11,
                'smoke detector': 39,
                'bluetooth speaker': 39,
                'desk lamp': 34,
                'blanket': 39,
                'mattress': 3,
                'laptop': 39,
                'book shelf': 9,
                'monitor light': 39,
                'sculpture': 39, 
                'toilet paper': 39,
                'pen': 39, 'eraser': 39, 'mousepad': 39,
                'kettle': 39, 'toaster': 39, 'salad spinner': 39,
                'pan': 39, 'hand vacuum': 39, 'microwave': 39, 'water filter': 39,
                'panel': 39, 'instant pot': 39, 'receipt': 39, 
                
                ### 3f15a9266d
                'painting': 10,
                'ceiling lamp': 34,
                'files': 22,  'file': 22, 'folders': 22, 'folder': 22,
                'paper towel': 26, 'safe box': 39,
                'pencil holder': 39, 'mouse pad': 39, 'exhaust fan': 39,
                'wall clock' :39
                }