# folder where the data is downloaded
data_root: /mnt/hdd/spp_benchmark_v3

# splits: [nvs_sem_train, nvs_sem_val]
scene_ids: ["dummy"]

# The following paths should be given relative to the DATA_ROOT/dslr/
# If not given, will use the default directory defined in ScannetppScene class

# input_image_dir: resized_images
# input_mask_dir: resized_anon_masks
# input_transforms_path: nerfstudio/transforms.json

downscale_factor: 1.0
# All use the relative path to DATA_ROOT/dslr/
out_image_dir: resized_images
out_mask_dir: resized_anon_masks
out_transforms_path: nerfstudio/transforms.json

# The folder name contains the undistortion results under data_root (e.g., data_root / folder_name)
folder_name: "data_undistorted_iphone"
